// import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs"
import {
  AiFillTwitterCircle, 
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiOutlineInstagram
} from "react-icons/ai"
import Image from "next/image"
import santi from "../../public/santi-avatar.png"
import design from "../../public/design.png"
import code from "../../public/code.png"
import consulting from "../../public/consulting.png"
import web1 from "../../public/web1.png"
import web2 from "../../public/web2.png"
import web3 from "../../public/web3.png"
import web4 from "../../public/web4.png"
import web5 from "../../public/web5.png"
import web6 from "../../public/web6.png"

export default function Home() {
  return (
      <div> 
        {/* <Head>
          <title> Santiago Bavaresco Portfolio</title>
          <meta name="description" content="Generated by create"/>
          <link rel="icon" href="/src/favicon.ico" />
        </Head> */}

        <main className='bg-gray-100 px-10 md:px-20 lg:px-60'>
          <section className='min-h-screen'>

            <nav className='py-10 mb-2 flex justify-between '>

              <h1 className='text-xl font-burtons'>developedBySanti</h1>

              <ul className='flex items-center'>
                <li>
                  <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
                </li>
                <li> 
                  <a className='
                    bg-gradient-to-r from-cyan-500 to-teal-500
                    text-white px-4 py-2 rounded-xl ml-8' 
                    href="#">
                      Resume
                  </a> 
                </li>
                <li></li>
                <li></li>
              </ul>

            </nav>

            <div className='text-center px-1'>
              <h2 className='text-5xl py-2 text-teal-500 font-medium md:text-7xl'>Santiago Bavaresco</h2>
              <h3 className='text-2xl py-2 md:text-4xl'>Fullstack Developer</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>
                Passionate about in software development and IT world, providing services for programming and tech infrastucture.
                Join me down below and let's get dive in!
              </p>
            </div>

            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>

              {/* <a> <AiFillTwitterCircle/> </a> */}
              <a> <AiFillGithub/> </a>
              <a> <AiFillLinkedin/> </a>
              <a> <AiOutlineInstagram/> </a>

            </div>

            <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 my-10 overflow-hidden md:h-96 md:w-96'>
              <Image src={santi} className="mt-2" layout="fill" objectFit="cover"/>
            </div>

          </section>

        {/* *************************************************************************** */}

        <section>
          <div>
            <h3 className="text-3xl py-1"> Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800"> 
              With a proactive, analytical, creative, professional with the capacity for planning, organization and team
              leadership; also with skills and criteria for decision making and <span className="text-teal-500">problem solving</span> labor problems, common
              sense, security and permanent dialogue <span className="text-teal-500">to meet the objectives</span> with different areas.
            </p>

            <p className="text-md py-2 leading-8 text-gray-800"> 
              I am very interested in technology, very patient, meticulous and manage to seek efficiency in the emerging
              problems that are presented to us in the world of programming. I'm excited to share that I have completed Henry's course in Full Stack Web Development.
            </p>
          </div>

          <div className="lg:flex gap-10">
            {/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */}
            <div className=" text-center shadow-lg p-10 rounded-xl my-10" >
              <div className="flex justify-center">
                <Image claseName="flex justify-center" src={design} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-4 pb-2"> Beutiful deings</h3>
                <p className="py-2"> Creating elegant desing suited fpr yput client</p>
              <h4 className="py-4 text-teal-600">Desing tools i use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Ilustrator</p>
                <p className="text-gray-800 py-1">Figma</p>
            </div>
            {/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */}
            <div className=" text-center shadow-lg p-10 rounded-xl my-10" >
              <div className="flex justify-center">
                <Image claseName="flex justify-center" src={code} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-4 pb-2"> Beutiful deings</h3>
                <p className="py-2"> Creating elegant desing suited fpr yput client</p>
              <h4 className="py-4 text-teal-600">Desing tools i use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Ilustrator</p>
                <p className="text-gray-800 py-1">Figma</p>
            </div>
            {/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */}
            <div className=" text-center shadow-2xl p-10 rounded-xl my-10" >
              <div className="flex justify-center">
                <Image claseName="flex justify-center" src={consulting} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-4 pb-2"> Beutiful deings</h3>
                <p className="py-2"> Creating elegant desing suited fpr yput client</p>
              <h4 className="py-4 text-teal-600">Desing tools i use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Ilustrator</p>
                <p className="text-gray-800 py-1">Figma</p>
            </div>
            {/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */}
          </div>
        </section>

        <section >
          <div >
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800"> 
              With a proactive, analytical, creative, professional with the capacity for planning, organization and team
              leadership; also with skills and criteria for decision making and <span className="text-teal-500">problem solving</span> labor problems, common
              sense, security and permanent dialogue <span className="text-teal-500">to meet the objectives</span> with different areas.
            </p>

            <p className="text-md py-2 leading-8 text-gray-800"> 
              I am very interested in technology, very patient, meticulous and manage to seek efficiency in the emerging
              problems that are presented to us in the world of programming. I'm excited to share that I have completed Henry's course in Full Stack Web Development.
            </p>
          </div>

          <div>
            <div><Image src={web1}/></div>
            <div><Image src={web2}/></div>
            <div><Image src={web3}/></div>
            <div><Image src={web4}/></div>
            <div><Image src={web5}/></div>
          </div>
        </section>

        </main>
      </div>



    // <main className="flex min-h-screen flex-col items-center justify-between p-24">
    //   <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
    //     <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
    //       Get started by editing&nbsp;
    //       <code className="font-mono font-bold">src/app/page.js</code>
    //     </p>
    //     <div className="fixed bottom-0 left-0 flex h-48 w-full items-end justify-center bg-gradient-to-t from-white via-white dark:from-black dark:via-black lg:static lg:h-auto lg:w-auto lg:bg-none">
    //       <a
    //         className="pointer-events-none flex place-items-center gap-2 p-8 lg:pointer-events-auto lg:p-0"
    //         href="https://vercel.com?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         By{' '}
    //         <Image
    //           src="/vercel.svg"
    //           alt="Vercel Logo"
    //           className="dark:invert"
    //           width={100}
    //           height={24}
    //           priority
    //         />
    //       </a>
    //     </div>
    //   </div>

    //   <div className="relative flex place-items-center before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[360px]">
    //     <Image
    //       className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
    //       src="/next.svg"
    //       alt="Next.js Logo"
    //       width={180}
    //       height={37}
    //       priority
    //     />
    //   </div>

    //   <div className="mb-32 grid text-center lg:mb-0 lg:grid-cols-4 lg:text-left">
    //     <a
    //       href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
    //       className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       <h2 className={`mb-3 text-2xl font-semibold`}>
    //         Do00000cs{' '}
    //         <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
    //           -&gt;
    //         </span>
    //       </h2>
    //       <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
    //         Find in-depth information about Next.js features and API.
    //       </p>
    //     </a>

    //     <a
    //       href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
    //       className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800 hover:dark:bg-opacity-30"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       <h2 className={`mb-3 text-2xl font-semibold`}>
    //         Learn{' '}
    //         <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
    //           -&gt;
    //         </span>
    //       </h2>
    //       <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
    //         Learn about Next.js in an interactive course with&nbsp;quizzes!
    //       </p>
    //     </a>

    //     <a
    //       href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
    //       className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       <h2 className={`mb-3 text-2xl font-semibold`}>
    //         Templates{' '}
    //         <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
    //           -&gt;
    //         </span>
    //       </h2>
    //       <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
    //         Explore the Next.js 13 playground.
    //       </p>
    //     </a>

    //     <a
    //       href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
    //       className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       <h2 className={`mb-3 text-2xl font-semibold`}>
    //         Deploy{' '}
    //         <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
    //           -&gt;
    //         </span>
    //       </h2>
    //       <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
    //         Instantly deploy your Next.js site to a shareable URL with Vercel.
    //       </p>
    //     </a>
    //   </div>
    // </main>
  )
}
